// <auto-generated />
using System;
using GSBC.Accounting.Grpc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GSBC.Accounting.Grpc.Data.Migrations
{
    [DbContext(typeof(AccountingDbContext))]
    [Migration("20260831073536_AddExpenseAttachments")]
    partial class AddExpenseAttachments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GSBC.Accounting.Grpc.Data.Models.Expenses.DbExpenseAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("LineId")
                        .HasColumnType("uuid");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId", "ContentHash")
                        .IsUnique();

                    b.ToTable("ExpenseAttachments");
                });

            modelBuilder.Entity("GSBC.Accounting.Grpc.Data.Models.Expenses.DbExpenseLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ChurchUsePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("GstAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LineDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId", "Ordinal");

                    b.ToTable("ExpenseLines");
                });

            modelBuilder.Entity("GSBC.Accounting.Grpc.Data.Models.Expenses.DbExpenseSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AmountCharged")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTimeOffset?>("ApprovalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("BankDetailsOnFile")
                        .HasColumnType("boolean");

                    b.Property<string>("BankReference")
                        .HasColumnType("text");

                    b.Property<string>("CardLastFourDigits")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("ContactPhoneEmail")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("EventProject")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ExpensePeriodFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpensePeriodTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FormDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GrossTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("GstTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<bool>("IsMockData")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LessPersonalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("MinistryDepartment")
                        .HasColumnType("text");

                    b.Property<decimal>("NetTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethodOther")
                        .HasColumnType("text");

                    b.Property<string>("PriorApprovalBy")
                        .HasColumnType("text");

                    b.Property<string>("PurposeActivity")
                        .HasColumnType("text");

                    b.Property<string>("PurposeNarrative")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<string>("RoleOther")
                        .HasColumnType("text");

                    b.Property<string>("SignatureName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubmitterName")
                        .HasColumnType("text");

                    b.Property<string>("SupplierMerchant")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionTime")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "CreatedAt");

                    b.ToTable("ExpenseSubmissions");
                });

            modelBuilder.Entity("GSBC.Accounting.Grpc.Data.Models.Expenses.DbExpenseAttachment", b =>
                {
                    b.HasOne("GSBC.Accounting.Grpc.Data.Models.Expenses.DbExpenseSubmission", "Submission")
                        .WithMany("Attachments")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("GSBC.Accounting.Grpc.Data.Models.Expenses.DbExpenseLine", b =>
                {
                    b.HasOne("GSBC.Accounting.Grpc.Data.Models.Expenses.DbExpenseSubmission", "Submission")
                        .WithMany("Lines")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("GSBC.Accounting.Grpc.Data.Models.Expenses.DbExpenseSubmission", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
